name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install onnxruntime
        pip install -e .

    - name: Run pytest - only "conversion" marker
      run: cd test && pytest -m "conversion"

    - name: Run Pytest - all except conversion marker
      run: cd test &&  pytest -m "not conversion"